### ISSUE TITLE
Context Examples

### ISSUE THREAD

**Issue by jeffersondarcy** [PacktPublishing/Simplifying-State-Management-in-React-Native#4]
Is there a particular reason for not using useContext hook in Context examples? <Context.Consumer> syntax looks super strange to me

**Comment by p-syche** [comment]
@jeffersondarcy thank you for your question :)

To be honest I find the `<Context.Consumer>` syntax easier for beginners: when using this syntax you know how everything is working. When using hooks the implementation is somewhat hidden. That's just my personal opinion though.
I agree that `<Context.Consumer>` looks weird and heavy-handed, but hopefully it brings value to someone who is learning about `context`.
